export interface DraftPick {
  round: number;
  manager: string;
  colOrder: number; // 1=Andrew ... 12=Patrick (spreadsheet left-to-right)
  player: string;
  isKeeper: boolean;
  isExtra: boolean; // rounds 26+, from traded picks
}

export const DRAFT_MANAGERS = [
  { fullName: "Andrew Bergoine", short: "Andrew", colOrder: 1 },
  { fullName: "Austin Brennen", short: "Austin", colOrder: 2 },
  { fullName: "Stephan Mattke", short: "Stephan", colOrder: 3 },
  { fullName: "Charley Tauer", short: "Charley", colOrder: 4 },
  { fullName: "Artie Arredondo", short: "Artie", colOrder: 5 },
  { fullName: "Josh", short: "Josh", colOrder: 6 },
  { fullName: "Mike Kyne", short: "Kyne", colOrder: 7 },
  { fullName: "Darren Cook", short: "Darren", colOrder: 8 },
  { fullName: "Will Harris", short: "Will", colOrder: 9 },
  { fullName: "Kevin Katsuda", short: "Kevin", colOrder: 10 },
  { fullName: "Mike Porter", short: "Porter", colOrder: 11 },
  { fullName: "Patrick Harvey", short: "Patrick", colOrder: 12 },
] as const;

export const DRAFT_PICKS: DraftPick[] = [
  { round:  1, colOrder:  1, manager: "Andrew Bergoine", player: "Tarik Skubal", isKeeper: false, isExtra: false },
  { round:  1, colOrder:  2, manager: "Austin Brennen", player: "Kyle Tucker", isKeeper: false, isExtra: false },
  { round:  1, colOrder:  4, manager: "Charley Tauer", player: "Yoshinobu Yamamoto", isKeeper: false, isExtra: false },
  { round:  1, colOrder:  4, manager: "Charley Tauer", player: "Fernando Tatis Jr.", isKeeper: false, isExtra: false },
  { round:  1, colOrder:  5, manager: "Artie Arredondo", player: "Aaron Judge", isKeeper: true, isExtra: false },
  { round:  1, colOrder:  6, manager: "Josh", player: "Ketel Marte", isKeeper: false, isExtra: false },
  { round:  1, colOrder:  7, manager: "Mike Kyne", player: "Logan Gilbert", isKeeper: false, isExtra: false },
  { round:  1, colOrder:  8, manager: "Darren Cook", player: "Bobby Witt Jr.", isKeeper: true, isExtra: false },
  { round:  1, colOrder:  9, manager: "Will Harris", player: "Corbin Carroll", isKeeper: false, isExtra: false },
  { round:  1, colOrder: 10, manager: "Kevin Katsuda", player: "Chris Sanchez", isKeeper: false, isExtra: false },
  { round:  1, colOrder: 11, manager: "Mike Porter", player: "Jose Ramirez", isKeeper: true, isExtra: false },
  { round:  1, colOrder: 12, manager: "Patrick Harvey", player: "Shohei Ohtani", isKeeper: true, isExtra: false },
  { round:  2, colOrder:  1, manager: "Andrew Bergoine", player: "Framber Valdez", isKeeper: false, isExtra: false },
  { round:  2, colOrder:  1, manager: "Andrew Bergoine", player: "Manny Machado", isKeeper: false, isExtra: false },
  { round:  2, colOrder:  2, manager: "Austin Brennen", player: "Freddy Peralta", isKeeper: false, isExtra: false },
  { round:  2, colOrder:  3, manager: "Stephan Mattke", player: "Chris Sale", isKeeper: false, isExtra: false },
  { round:  2, colOrder:  4, manager: "Charley Tauer", player: "Cristian Hernandez", isKeeper: false, isExtra: false },
  { round:  2, colOrder:  5, manager: "Artie Arredondo", player: "Alex Bregman", isKeeper: false, isExtra: false },
  { round:  2, colOrder:  6, manager: "Josh", player: "Yordan Alvarez", isKeeper: false, isExtra: false },
  { round:  2, colOrder:  7, manager: "Mike Kyne", player: "Francisco Lindor", isKeeper: false, isExtra: false },
  { round:  2, colOrder:  9, manager: "Will Harris", player: "Hunter Brown", isKeeper: false, isExtra: false },
  { round:  2, colOrder: 10, manager: "Kevin Katsuda", player: "Max Fried", isKeeper: false, isExtra: false },
  { round:  2, colOrder: 11, manager: "Mike Porter", player: "Gunnar Henderson", isKeeper: false, isExtra: false },
  { round:  2, colOrder: 12, manager: "Patrick Harvey", player: "Kyle Schwarber", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  1, manager: "Andrew Bergoine", player: "William Contreras", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  1, manager: "Andrew Bergoine", player: "Joe Ryan", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  2, manager: "Austin Brennen", player: "Pete Alonso", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  2, manager: "Austin Brennen", player: "Cody Bellinger", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  2, manager: "Austin Brennen", player: "Bo Bichette", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  4, manager: "Charley Tauer", player: "George Kirby", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  4, manager: "Charley Tauer", player: "Jazz Chisholm", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  5, manager: "Artie Arredondo", player: "Elly de la Cruz", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  6, manager: "Josh", player: "Rafael Devers", isKeeper: false, isExtra: false },
  { round:  3, colOrder:  7, manager: "Mike Kyne", player: "Mookie Betts", isKeeper: false, isExtra: false },
  { round:  3, colOrder: 10, manager: "Kevin Katsuda", player: "Dylan Cease", isKeeper: false, isExtra: false },
  { round:  3, colOrder: 12, manager: "Patrick Harvey", player: "Paul Skenes", isKeeper: true, isExtra: false },
  { round:  4, colOrder:  1, manager: "Andrew Bergoine", player: "Steven Kwan", isKeeper: false, isExtra: false },
  { round:  4, colOrder:  1, manager: "Andrew Bergoine", player: "Jose Altuve", isKeeper: false, isExtra: false },
  { round:  4, colOrder:  2, manager: "Austin Brennen", player: "Luis Arraez", isKeeper: false, isExtra: false },
  { round:  4, colOrder:  2, manager: "Austin Brennen", player: "Cole Ragans", isKeeper: false, isExtra: false },
  { round:  4, colOrder:  2, manager: "Austin Brennen", player: "Trea Turner", isKeeper: false, isExtra: false },
  { round:  4, colOrder:  3, manager: "Stephan Mattke", player: "Sonny Gray", isKeeper: false, isExtra: false },
  { round:  4, colOrder:  3, manager: "Stephan Mattke", player: "Kevin Gausman", isKeeper: false, isExtra: false },
  { round:  4, colOrder:  4, manager: "Charley Tauer", player: "Ronald Acuna", isKeeper: true, isExtra: false },
  { round:  4, colOrder:  5, manager: "Artie Arredondo", player: "Vladimir Guerrero Jr.", isKeeper: true, isExtra: false },
  { round:  4, colOrder:  6, manager: "Josh", player: "Bryce Harper", isKeeper: false, isExtra: false },
  { round:  4, colOrder:  7, manager: "Mike Kyne", player: "Ryan Pepiot", isKeeper: false, isExtra: false },
  { round:  4, colOrder: 10, manager: "Kevin Katsuda", player: "Nick Pivetta", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  1, manager: "Andrew Bergoine", player: "Jackson Merrill", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  2, manager: "Austin Brennen", player: "George Springer", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  3, manager: "Stephan Mattke", player: "Nathan Eovaldi", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  4, manager: "Charley Tauer", player: "Riley Greene", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  4, manager: "Charley Tauer", player: "Nolan McLain", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  5, manager: "Artie Arredondo", player: "Freddie Freeman", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  6, manager: "Josh", player: "Maikel Garcia", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  7, manager: "Mike Kyne", player: "Josh Naylor", isKeeper: false, isExtra: false },
  { round:  5, colOrder:  9, manager: "Will Harris", player: "Mason Miller", isKeeper: false, isExtra: false },
  { round:  5, colOrder: 10, manager: "Kevin Katsuda", player: "Matt Olson", isKeeper: false, isExtra: false },
  { round:  5, colOrder: 11, manager: "Mike Porter", player: "Tyler Glas", isKeeper: false, isExtra: false },
  { round:  5, colOrder: 12, manager: "Patrick Harvey", player: "Ben Rice", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  1, manager: "Andrew Bergoine", player: "Corey Seager", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  2, manager: "Austin Brennen", player: "Geraldo Perdomo", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  3, manager: "Stephan Mattke", player: "Austin Riley", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  4, manager: "Charley Tauer", player: "Drew Rasmussen", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  4, manager: "Charley Tauer", player: "CJ Abrams", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  5, manager: "Artie Arredondo", player: "Luis Castillo", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  6, manager: "Josh", player: "Julio Rodriguez", isKeeper: true, isExtra: false },
  { round:  6, colOrder:  7, manager: "Mike Kyne", player: "Eugenio Suarez", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  8, manager: "Darren Cook", player: "Teoscar Hernández", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  8, manager: "Darren Cook", player: "Robbie Ray", isKeeper: false, isExtra: false },
  { round:  6, colOrder:  9, manager: "Will Harris", player: "Hunter Goodman", isKeeper: false, isExtra: false },
  { round:  6, colOrder: 10, manager: "Kevin Katsuda", player: "Spencer Strider", isKeeper: false, isExtra: false },
  { round:  7, colOrder:  1, manager: "Andrew Bergoine", player: "Sal Perez", isKeeper: false, isExtra: false },
  { round:  7, colOrder:  3, manager: "Stephan Mattke", player: "Tyler Soderstrom", isKeeper: false, isExtra: false },
  { round:  7, colOrder:  4, manager: "Charley Tauer", player: "Michael King", isKeeper: false, isExtra: false },
  { round:  7, colOrder:  5, manager: "Artie Arredondo", player: "Byron Buxton", isKeeper: false, isExtra: false },
  { round:  7, colOrder:  6, manager: "Josh", player: "Juan Soto", isKeeper: true, isExtra: false },
  { round:  7, colOrder:  6, manager: "Josh", player: "Bryan Woo", isKeeper: true, isExtra: false },
  { round:  7, colOrder:  7, manager: "Mike Kyne", player: "Brandon Nimmo", isKeeper: false, isExtra: false },
  { round:  7, colOrder:  8, manager: "Darren Cook", player: "Cal Raleigh", isKeeper: true, isExtra: false },
  { round:  7, colOrder:  9, manager: "Will Harris", player: "Brice Turang", isKeeper: false, isExtra: false },
  { round:  7, colOrder: 10, manager: "Kevin Katsuda", player: "Yandy Diaz", isKeeper: false, isExtra: false },
  { round:  7, colOrder: 11, manager: "Mike Porter", player: "Sandy Alcantara", isKeeper: false, isExtra: false },
  { round:  7, colOrder: 12, manager: "Patrick Harvey", player: "Blake Snell", isKeeper: false, isExtra: false },
  { round:  8, colOrder:  1, manager: "Andrew Bergoine", player: "Seiya Suzuki", isKeeper: false, isExtra: false },
  { round:  8, colOrder:  3, manager: "Stephan Mattke", player: "Tatsuya Imai", isKeeper: false, isExtra: false },
  { round:  8, colOrder:  4, manager: "Charley Tauer", player: "Shea Langliers", isKeeper: false, isExtra: false },
  { round:  8, colOrder:  4, manager: "Charley Tauer", player: "Kazuma Okamoto", isKeeper: false, isExtra: false },
  { round:  8, colOrder:  5, manager: "Artie Arredondo", player: "Zac Gallen", isKeeper: false, isExtra: false },
  { round:  8, colOrder:  7, manager: "Mike Kyne", player: "Tanner Bibee", isKeeper: false, isExtra: false },
  { round:  8, colOrder:  8, manager: "Darren Cook", player: "Aaron Nola", isKeeper: false, isExtra: false },
  { round:  8, colOrder:  9, manager: "Will Harris", player: "Alec Burleson", isKeeper: false, isExtra: false },
  { round:  8, colOrder: 10, manager: "Kevin Katsuda", player: "Jacob Wilson", isKeeper: false, isExtra: false },
  { round:  8, colOrder: 10, manager: "Kevin Katsuda", player: "Nick Lodolo", isKeeper: false, isExtra: false },
  { round:  8, colOrder: 11, manager: "Mike Porter", player: "Trevor Rogers", isKeeper: false, isExtra: false },
  { round:  8, colOrder: 12, manager: "Patrick Harvey", player: "Ozzie Albies", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  1, manager: "Andrew Bergoine", player: "Ranger Suarez", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  2, manager: "Austin Brennen", player: "Logan Webb", isKeeper: true, isExtra: false },
  { round:  9, colOrder:  2, manager: "Austin Brennen", player: "Gavin Williams", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  3, manager: "Stephan Mattke", player: "Augustin Ramirez", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  4, manager: "Charley Tauer", player: "Oneil Cruz", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  5, manager: "Artie Arredondo", player: "Randy Arozarena", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  6, manager: "Josh", player: "Shota Imanaga", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  7, manager: "Mike Kyne", player: "Jo Adell", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  8, manager: "Darren Cook", player: "Kyle Stowers", isKeeper: false, isExtra: false },
  { round:  9, colOrder:  9, manager: "Will Harris", player: "Edwin Díaz", isKeeper: false, isExtra: false },
  { round:  9, colOrder: 11, manager: "Mike Porter", player: "Christian Yelich", isKeeper: false, isExtra: false },
  { round:  9, colOrder: 11, manager: "Mike Porter", player: "Zack Wheeler", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  1, manager: "Andrew Bergoine", player: "Andrés Muñoz", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  2, manager: "Austin Brennen", player: "Carlos Rodón", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  2, manager: "Austin Brennen", player: "Emmet Sheehan", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  2, manager: "Austin Brennen", player: "Cade Smith", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  4, manager: "Charley Tauer", player: "Jho Duran", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  4, manager: "Charley Tauer", player: "Trey Yesavage", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  6, manager: "Josh", player: "Andrew Abbott", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  6, manager: "Josh", player: "Jeremy Peña", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  7, manager: "Mike Kyne", player: "Bryan Reynolds", isKeeper: false, isExtra: false },
  { round: 10, colOrder:  9, manager: "Will Harris", player: "Jac Caglianone", isKeeper: false, isExtra: false },
  { round: 10, colOrder: 10, manager: "Kevin Katsuda", player: "MacKenzie Gore", isKeeper: false, isExtra: false },
  { round: 10, colOrder: 12, manager: "Patrick Harvey", player: "Matt Chapman", isKeeper: false, isExtra: false },
  { round: 11, colOrder:  1, manager: "Andrew Bergoine", player: "Ian Happ", isKeeper: false, isExtra: false },
  { round: 11, colOrder:  1, manager: "Andrew Bergoine", player: "Devin Williams", isKeeper: false, isExtra: false },
  { round: 11, colOrder:  2, manager: "Austin Brennen", player: "Matthew Boyd", isKeeper: false, isExtra: false },
  { round: 11, colOrder:  3, manager: "Stephan Mattke", player: "Willy Adames", isKeeper: false, isExtra: false },
  { round: 11, colOrder:  4, manager: "Charley Tauer", player: "David Bednar", isKeeper: false, isExtra: false },
  { round: 11, colOrder:  4, manager: "Charley Tauer", player: "Brandon Woodruff", isKeeper: false, isExtra: false },
  { round: 11, colOrder:  5, manager: "Artie Arredondo", player: "Shane Baz", isKeeper: false, isExtra: false },
  { round: 11, colOrder:  6, manager: "Josh", player: "Kris Bubic", isKeeper: false, isExtra: false },
  { round: 11, colOrder: 10, manager: "Kevin Katsuda", player: "Drake Baldwin", isKeeper: false, isExtra: false },
  { round: 11, colOrder: 11, manager: "Mike Porter", player: "Sal Stewart", isKeeper: false, isExtra: false },
  { round: 11, colOrder: 11, manager: "Mike Porter", player: "Luke Keaschall", isKeeper: false, isExtra: false },
  { round: 11, colOrder: 12, manager: "Patrick Harvey", player: "Adley Rutschman", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  1, manager: "Andrew Bergoine", player: "Raisel Iglesias", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  1, manager: "Andrew Bergoine", player: "Ezequiel Tovar", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  2, manager: "Austin Brennen", player: "Isaac Paredes", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  2, manager: "Austin Brennen", player: "Bryan Abreu", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  3, manager: "Stephan Mattke", player: "Jack Leiter", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  4, manager: "Charley Tauer", player: "Christian Walker", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  5, manager: "Artie Arredondo", player: "Yanier Diaz", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  6, manager: "Josh", player: "Ryan Weathers", isKeeper: false, isExtra: false },
  { round: 12, colOrder:  9, manager: "Will Harris", player: "Andy Pages", isKeeper: false, isExtra: false },
  { round: 12, colOrder: 10, manager: "Kevin Katsuda", player: "Michael Harris II", isKeeper: false, isExtra: false },
  { round: 12, colOrder: 10, manager: "Kevin Katsuda", player: "Will Smith", isKeeper: false, isExtra: false },
  { round: 12, colOrder: 12, manager: "Patrick Harvey", player: "Aroldis Chapman", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  1, manager: "Andrew Bergoine", player: "Jakob Marsee", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  2, manager: "Austin Brennen", player: "E Cabrera", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  3, manager: "Stephan Mattke", player: "Konnor Griffin", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  3, manager: "Stephan Mattke", player: "Matt McClain", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  5, manager: "Artie Arredondo", player: "Daylen Lile", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  6, manager: "Josh", player: "Kodai Senga", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  7, manager: "Mike Kyne", player: "Jackson Holliday", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  8, manager: "Darren Cook", player: "Shane Maclanahan", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  8, manager: "Darren Cook", player: "Luis Robert", isKeeper: false, isExtra: false },
  { round: 13, colOrder:  9, manager: "Will Harris", player: "Jorge Polanco", isKeeper: false, isExtra: false },
  { round: 13, colOrder: 10, manager: "Kevin Katsuda", player: "Gerrit Cole", isKeeper: false, isExtra: false },
  { round: 13, colOrder: 12, manager: "Patrick Harvey", player: "Jack Flaherty", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  1, manager: "Andrew Bergoine", player: "Sal Frelick", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  2, manager: "Austin Brennen", player: "Griffin Jax", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  2, manager: "Austin Brennen", player: "Gleybar Torres", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  3, manager: "Stephan Mattke", player: "Dansby Swanson", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  4, manager: "Charley Tauer", player: "Brandon Lowe", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  6, manager: "Josh", player: "Ivan Herrera", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  6, manager: "Josh", player: "Jonathan Aranda", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  7, manager: "Mike Kyne", player: "Kerry Carpenter", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  8, manager: "Darren Cook", player: "Seth Lugo", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  8, manager: "Darren Cook", player: "Heliot Ramos", isKeeper: false, isExtra: false },
  { round: 14, colOrder:  9, manager: "Will Harris", player: "Jose Soriano", isKeeper: false, isExtra: false },
  { round: 14, colOrder: 11, manager: "Mike Porter", player: "Munetaka Murakami", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  1, manager: "Andrew Bergoine", player: "Joey Cantillo", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  2, manager: "Austin Brennen", player: "Jacob de Grom", isKeeper: true, isExtra: false },
  { round: 15, colOrder:  4, manager: "Charley Tauer", player: "Yennier Ponce", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  4, manager: "Charley Tauer", player: "Josh Hader", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  5, manager: "Artie Arredondo", player: "Samuel Basallo", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  6, manager: "Josh", player: "Will Warren", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  6, manager: "Josh", player: "JJ Weatherholt", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  7, manager: "Mike Kyne", player: "Ceddanne Rafaela", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  7, manager: "Mike Kyne", player: "Grayson Rodriguez", isKeeper: false, isExtra: false },
  { round: 15, colOrder:  8, manager: "Darren Cook", player: "Brendan Donovan", isKeeper: false, isExtra: false },
  { round: 15, colOrder: 11, manager: "Mike Porter", player: "Noah Cameron", isKeeper: false, isExtra: false },
  { round: 15, colOrder: 11, manager: "Mike Porter", player: "Ryne Nelson", isKeeper: false, isExtra: false },
  { round: 15, colOrder: 11, manager: "Mike Porter", player: "Daulton Varsho", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  1, manager: "Andrew Bergoine", player: "Shane Bieber", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  2, manager: "Austin Brennen", player: "Carter Jensen", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  3, manager: "Stephan Mattke", player: "Emilio Pagán", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  5, manager: "Artie Arredondo", player: "Marcus Semien", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  6, manager: "Josh", player: "Zach Eflin", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  7, manager: "Mike Kyne", player: "Pete Fairbanks", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  8, manager: "Darren Cook", player: "Willson Contreras", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  9, manager: "Will Harris", player: "Kevin McGonigle", isKeeper: false, isExtra: false },
  { round: 16, colOrder:  9, manager: "Will Harris", player: "Addison Barger", isKeeper: false, isExtra: false },
  { round: 16, colOrder: 10, manager: "Kevin Katsuda", player: "Xavier Edwards", isKeeper: false, isExtra: false },
  { round: 16, colOrder: 11, manager: "Mike Porter", player: "Mike Burrows", isKeeper: false, isExtra: false },
  { round: 16, colOrder: 12, manager: "Patrick Harvey", player: "Jung Hoo Lee", isKeeper: false, isExtra: false },
  { round: 17, colOrder:  1, manager: "Andrew Bergoine", player: "Jordan Westburg", isKeeper: false, isExtra: false },
  { round: 17, colOrder:  3, manager: "Stephan Mattke", player: "Bryce Miller", isKeeper: false, isExtra: false },
  { round: 17, colOrder:  3, manager: "Stephan Mattke", player: "Shane Smith", isKeeper: false, isExtra: false },
  { round: 17, colOrder:  4, manager: "Charley Tauer", player: "José Caballero", isKeeper: false, isExtra: false },
  { round: 17, colOrder:  5, manager: "Artie Arredondo", player: "Logan Henderson", isKeeper: false, isExtra: false },
  { round: 17, colOrder:  6, manager: "Josh", player: "Merrill Kelly", isKeeper: false, isExtra: false },
  { round: 17, colOrder:  7, manager: "Mike Kyne", player: "Jesus Luzardo", isKeeper: true, isExtra: false },
  { round: 17, colOrder:  8, manager: "Darren Cook", player: "Yusei Kikuchi", isKeeper: false, isExtra: false },
  { round: 17, colOrder:  9, manager: "Will Harris", player: "Matthew Liberatore", isKeeper: false, isExtra: false },
  { round: 17, colOrder: 10, manager: "Kevin Katsuda", player: "Ernie Clement", isKeeper: false, isExtra: false },
  { round: 17, colOrder: 11, manager: "Mike Porter", player: "Kyle Harrison", isKeeper: false, isExtra: false },
  { round: 17, colOrder: 12, manager: "Patrick Harvey", player: "Joe Musgrove", isKeeper: false, isExtra: false },
  { round: 18, colOrder:  5, manager: "Artie Arredondo", player: "Braxton Ashcraft", isKeeper: false, isExtra: false },
  { round: 18, colOrder:  6, manager: "Josh", player: "Andrew Painter", isKeeper: false, isExtra: false },
  { round: 18, colOrder:  7, manager: "Mike Kyne", player: "Alejandro Kirk", isKeeper: false, isExtra: false },
  { round: 18, colOrder:  8, manager: "Darren Cook", player: "Caleb Durbin", isKeeper: false, isExtra: false },
  { round: 18, colOrder:  9, manager: "Will Harris", player: "Cade Cavalli", isKeeper: false, isExtra: false },
  { round: 18, colOrder:  9, manager: "Will Harris", player: "Lawrence Butler", isKeeper: false, isExtra: false },
  { round: 18, colOrder: 10, manager: "Kevin Katsuda", player: "Noelvi Marte", isKeeper: false, isExtra: false },
  { round: 18, colOrder: 10, manager: "Kevin Katsuda", player: "Brayan Bello", isKeeper: false, isExtra: false },
  { round: 18, colOrder: 11, manager: "Mike Porter", player: "Mick Abel", isKeeper: false, isExtra: false },
  { round: 18, colOrder: 12, manager: "Patrick Harvey", player: "Trevor Story", isKeeper: false, isExtra: false },
  { round: 18, colOrder: 12, manager: "Patrick Harvey", player: "Adolis Garcia", isKeeper: false, isExtra: false },
  { round: 19, colOrder:  3, manager: "Stephan Mattke", player: "Chase DeLauter", isKeeper: false, isExtra: false },
  { round: 19, colOrder:  3, manager: "Stephan Mattke", player: "Marcell Ozuna", isKeeper: false, isExtra: false },
  { round: 19, colOrder:  5, manager: "Artie Arredondo", player: "Mike Trout", isKeeper: false, isExtra: false },
  { round: 19, colOrder:  5, manager: "Artie Arredondo", player: "Jordan Lawlar", isKeeper: false, isExtra: false },
  { round: 19, colOrder:  7, manager: "Mike Kyne", player: "Max Meyer", isKeeper: false, isExtra: false },
  { round: 19, colOrder:  8, manager: "Darren Cook", player: "Walker Buehler", isKeeper: false, isExtra: false },
  { round: 19, colOrder: 10, manager: "Kevin Katsuda", player: "Jeremiah Estrada", isKeeper: false, isExtra: false },
  { round: 19, colOrder: 11, manager: "Mike Porter", player: "Francisco Álvarez", isKeeper: false, isExtra: false },
  { round: 19, colOrder: 11, manager: "Mike Porter", player: "Ramón Laureano", isKeeper: false, isExtra: false },
  { round: 19, colOrder: 12, manager: "Patrick Harvey", player: "Roman Anthony", isKeeper: true, isExtra: false },
  { round: 19, colOrder: 12, manager: "Patrick Harvey", player: "Dylan Crews", isKeeper: false, isExtra: false },
  { round: 20, colOrder:  2, manager: "Austin Brennen", player: "Wilyer Abreu", isKeeper: false, isExtra: false },
  { round: 20, colOrder:  3, manager: "Stephan Mattke", player: "Chris Bassitt", isKeeper: false, isExtra: false },
  { round: 20, colOrder:  5, manager: "Artie Arredondo", player: "Ryan Helsley", isKeeper: false, isExtra: false },
  { round: 20, colOrder:  6, manager: "Josh", player: "Gabriel Moreno", isKeeper: false, isExtra: false },
  { round: 20, colOrder:  7, manager: "Mike Kyne", player: "Grant Taylor", isKeeper: false, isExtra: false },
  { round: 20, colOrder:  8, manager: "Darren Cook", player: "Carlos Correa", isKeeper: false, isExtra: false },
  { round: 20, colOrder:  9, manager: "Will Harris", player: "Garrett Crochet", isKeeper: true, isExtra: false },
  { round: 20, colOrder: 10, manager: "Kevin Katsuda", player: "Junior Caminero", isKeeper: true, isExtra: false },
  { round: 20, colOrder: 10, manager: "Kevin Katsuda", player: "Brent Rooker", isKeeper: true, isExtra: false },
  { round: 20, colOrder: 11, manager: "Mike Porter", player: "James Wood", isKeeper: true, isExtra: false },
  { round: 20, colOrder: 12, manager: "Patrick Harvey", player: "Brenton Doyle", isKeeper: false, isExtra: false },
  { round: 20, colOrder: 12, manager: "Patrick Harvey", player: "Payton Tolle", isKeeper: false, isExtra: false },
  { round: 21, colOrder:  3, manager: "Stephan Mattke", player: "Pete Crow-Armstrong", isKeeper: true, isExtra: false },
  { round: 21, colOrder:  3, manager: "Stephan Mattke", player: "Jeff Hoffman", isKeeper: false, isExtra: false },
  { round: 21, colOrder:  5, manager: "Artie Arredondo", player: "Leo De Vries", isKeeper: false, isExtra: false },
  { round: 21, colOrder:  8, manager: "Darren Cook", player: "Bryce Eldridge", isKeeper: false, isExtra: false },
  { round: 21, colOrder:  9, manager: "Will Harris", player: "Dustin May", isKeeper: false, isExtra: false },
  { round: 21, colOrder:  9, manager: "Will Harris", player: "Brandon Sproat", isKeeper: false, isExtra: false },
  { round: 21, colOrder: 10, manager: "Kevin Katsuda", player: "Abner Uribe", isKeeper: false, isExtra: false },
  { round: 21, colOrder: 11, manager: "Mike Porter", player: "Hunter Greene", isKeeper: false, isExtra: false },
  { round: 21, colOrder: 12, manager: "Patrick Harvey", player: "Carlos Estevez", isKeeper: false, isExtra: false },
  { round: 22, colOrder:  1, manager: "Andrew Bergoine", player: "Nico Hoerner", isKeeper: true, isExtra: false },
  { round: 22, colOrder:  5, manager: "Artie Arredondo", player: "Roki Sasaki", isKeeper: false, isExtra: false },
  { round: 22, colOrder:  8, manager: "Darren Cook", player: "Reynaldo Lopez", isKeeper: false, isExtra: false },
  { round: 22, colOrder:  9, manager: "Will Harris", player: "Brett Baty", isKeeper: false, isExtra: false },
  { round: 22, colOrder: 10, manager: "Kevin Katsuda", player: "Brady Singer", isKeeper: false, isExtra: false },
  { round: 22, colOrder: 10, manager: "Kevin Katsuda", player: "Ben Brown", isKeeper: false, isExtra: false },
  { round: 22, colOrder: 11, manager: "Mike Porter", player: "Spencer Arrighetti", isKeeper: false, isExtra: false },
  { round: 22, colOrder: 12, manager: "Patrick Harvey", player: "Jasson Dominguez", isKeeper: false, isExtra: false },
  { round: 23, colOrder:  1, manager: "Andrew Bergoine", player: "Spencer Torkelson", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  1, manager: "Andrew Bergoine", player: "Cade Horton", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  2, manager: "Austin Brennen", player: "Nick Kurtz", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  3, manager: "Stephan Mattke", player: "Taylor Ward", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  3, manager: "Stephan Mattke", player: "Cam Schlittler", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  4, manager: "Charley Tauer", player: "Jacob Misiorowski", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  4, manager: "Charley Tauer", player: "Vinnie Pasquantino", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  5, manager: "Artie Arredondo", player: "Bubba Chandler", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  6, manager: "Josh", player: "Parker Messick", isKeeper: false, isExtra: false },
  { round: 23, colOrder:  7, manager: "Mike Kyne", player: "Michael Busch", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  7, manager: "Mike Kyne", player: "Chase Burns", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  8, manager: "Darren Cook", player: "Eury Perez", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  9, manager: "Will Harris", player: "Kyle Bradish", isKeeper: true, isExtra: false },
  { round: 23, colOrder:  9, manager: "Will Harris", player: "Zach Neto", isKeeper: true, isExtra: false },
  { round: 23, colOrder: 10, manager: "Kevin Katsuda", player: "Jarren Duran", isKeeper: true, isExtra: false },
  { round: 23, colOrder: 11, manager: "Mike Porter", player: "Wyatt Langford", isKeeper: true, isExtra: false },
  { round: 23, colOrder: 12, manager: "Patrick Harvey", player: "Garrett Whitlock", isKeeper: false, isExtra: false },
  { round: 24, colOrder:  3, manager: "Stephan Mattke", player: "J Springs", isKeeper: false, isExtra: false },
  { round: 24, colOrder:  5, manager: "Artie Arredondo", player: "Daniel Palencia", isKeeper: false, isExtra: false },
  { round: 24, colOrder:  6, manager: "Josh", player: "Spencer Schwellenbach", isKeeper: false, isExtra: false },
  { round: 24, colOrder:  7, manager: "Mike Kyne", player: "Taj Bradley", isKeeper: false, isExtra: false },
  { round: 24, colOrder:  8, manager: "Darren Cook", player: "Cristian Javier", isKeeper: false, isExtra: false },
  { round: 24, colOrder:  9, manager: "Will Harris", player: "Jared Jones", isKeeper: false, isExtra: false },
  { round: 24, colOrder: 11, manager: "Mike Porter", player: "Trevor Megill", isKeeper: false, isExtra: false },
  { round: 24, colOrder: 12, manager: "Patrick Harvey", player: "Trevor Larnach", isKeeper: false, isExtra: false },
  { round: 24, colOrder: 12, manager: "Patrick Harvey", player: "Joey Loperfido", isKeeper: false, isExtra: false },
  { round: 25, colOrder:  3, manager: "Stephan Mattke", player: "Miguel Vargas", isKeeper: false, isExtra: false },
  { round: 25, colOrder:  5, manager: "Artie Arredondo", player: "Josh Smith", isKeeper: false, isExtra: false },
  { round: 25, colOrder:  6, manager: "Josh", player: "Colton Cowser", isKeeper: false, isExtra: false },
  { round: 25, colOrder:  7, manager: "Mike Kyne", player: "Garrett Cleavinger", isKeeper: false, isExtra: false },
  { round: 25, colOrder:  8, manager: "Darren Cook", player: "Cam Smith", isKeeper: false, isExtra: false },
  { round: 25, colOrder:  9, manager: "Will Harris", player: "Drew Anderson", isKeeper: false, isExtra: false },
  { round: 25, colOrder: 11, manager: "Mike Porter", player: "Kenley Jansen", isKeeper: false, isExtra: false },
  { round: 25, colOrder: 12, manager: "Patrick Harvey", player: "A.J. Puk", isKeeper: false, isExtra: false },
  { round: 26, colOrder:  5, manager: "Artie Arredondo", player: "Seranthony Dominguez", isKeeper: false, isExtra: true },
  { round: 26, colOrder:  7, manager: "Mike Kyne", player: "Bailey Ober", isKeeper: false, isExtra: true },
  { round: 26, colOrder:  8, manager: "Darren Cook", player: "Coby Mayo", isKeeper: false, isExtra: true },
  { round: 26, colOrder:  9, manager: "Will Harris", player: "Johan Oviedo", isKeeper: false, isExtra: true },
  { round: 26, colOrder: 11, manager: "Mike Porter", player: "Adrian Morejon", isKeeper: false, isExtra: true },
  { round: 26, colOrder: 12, manager: "Patrick Harvey", player: "Colin Holderman", isKeeper: false, isExtra: true },
  { round: 27, colOrder:  7, manager: "Mike Kyne", player: "Carson Benge", isKeeper: false, isExtra: true },
  { round: 27, colOrder:  8, manager: "Darren Cook", player: "Marcelo Mayer", isKeeper: false, isExtra: true },
  { round: 28, colOrder:  8, manager: "Darren Cook", player: "Corbin Burns", isKeeper: false, isExtra: true },
  { round: 29, colOrder:  8, manager: "Darren Cook", player: "Ryan Walker", isKeeper: false, isExtra: true },
];
