export interface DraftPick {
  round: number;
  manager: string;
  draftOrder: number;
  player: string;
  isKeeper: boolean;
  isExtra: boolean; // rounds 26+, from traded picks
}

export const DRAFT_MANAGERS = [
  { fullName: "Patrick Harvey", short: "Patrick", draftOrder: 1 },
  { fullName: "Mike Porter", short: "Porter", draftOrder: 2 },
  { fullName: "Kevin Katsuda", short: "Kevin", draftOrder: 3 },
  { fullName: "Will Harris", short: "Will", draftOrder: 4 },
  { fullName: "Darren Cook", short: "Darren", draftOrder: 5 },
  { fullName: "Mike Kyne", short: "Kyne", draftOrder: 6 },
  { fullName: "Josh", short: "Josh", draftOrder: 7 },
  { fullName: "Artie Arredondo", short: "Artie", draftOrder: 8 },
  { fullName: "Andrew Bergoine", short: "Andrew", draftOrder: 9 },
  { fullName: "Austin Brennen", short: "Austin", draftOrder: 10 },
  { fullName: "Stephan Mattke", short: "Stephan", draftOrder: 11 },
  { fullName: "Charley Tauer", short: "Charley", draftOrder: 12 },
] as const;

export const DRAFT_PICKS: DraftPick[] = [
  { round:  1, draftOrder:  1, manager: "Patrick Harvey", player: "Shohei Ohtani", isKeeper: true, isExtra: false },
  { round:  1, draftOrder:  2, manager: "Mike Porter", player: "Jose Ramirez", isKeeper: true, isExtra: false },
  { round:  1, draftOrder:  3, manager: "Kevin Katsuda", player: "Chris Sanchez", isKeeper: false, isExtra: false },
  { round:  1, draftOrder:  4, manager: "Will Harris", player: "Corbin Carroll", isKeeper: false, isExtra: false },
  { round:  1, draftOrder:  5, manager: "Darren Cook", player: "Bobby Witt Jr.", isKeeper: true, isExtra: false },
  { round:  1, draftOrder:  6, manager: "Mike Kyne", player: "Logan Gilbert", isKeeper: false, isExtra: false },
  { round:  1, draftOrder:  7, manager: "Josh", player: "Marte", isKeeper: false, isExtra: false },
  { round:  1, draftOrder:  8, manager: "Artie Arredondo", player: "Aaron Judge", isKeeper: true, isExtra: false },
  { round:  1, draftOrder:  9, manager: "Andrew Bergoine", player: "Skubal", isKeeper: false, isExtra: false },
  { round:  1, draftOrder: 10, manager: "Austin Brennen", player: "Tucker", isKeeper: false, isExtra: false },
  { round:  1, draftOrder: 12, manager: "Charley Tauer", player: "Yamamoto", isKeeper: false, isExtra: false },
  { round:  1, draftOrder: 12, manager: "Charley Tauer", player: "Tatis", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  1, manager: "Patrick Harvey", player: "Schwarber", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  2, manager: "Mike Porter", player: "Gunnar Henderson", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  3, manager: "Kevin Katsuda", player: "Max Fried", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  4, manager: "Will Harris", player: "Hunter Brown", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  6, manager: "Mike Kyne", player: "Lindor", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  7, manager: "Josh", player: "Yordan", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  8, manager: "Artie Arredondo", player: "Bregman", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  9, manager: "Andrew Bergoine", player: "Framber", isKeeper: false, isExtra: false },
  { round:  2, draftOrder:  9, manager: "Andrew Bergoine", player: "Machado", isKeeper: false, isExtra: false },
  { round:  2, draftOrder: 10, manager: "Austin Brennen", player: "Freddy Peralta", isKeeper: false, isExtra: false },
  { round:  2, draftOrder: 11, manager: "Stephan Mattke", player: "Sale", isKeeper: false, isExtra: false },
  { round:  2, draftOrder: 12, manager: "Charley Tauer", player: "Cristian Hernandez", isKeeper: false, isExtra: false },
  { round:  3, draftOrder:  1, manager: "Patrick Harvey", player: "Paul Skenes", isKeeper: true, isExtra: false },
  { round:  3, draftOrder:  3, manager: "Kevin Katsuda", player: "Dylan Cease", isKeeper: false, isExtra: false },
  { round:  3, draftOrder:  6, manager: "Mike Kyne", player: "Mookie", isKeeper: false, isExtra: false },
  { round:  3, draftOrder:  7, manager: "Josh", player: "Devers", isKeeper: false, isExtra: false },
  { round:  3, draftOrder:  8, manager: "Artie Arredondo", player: "Elly de la Cruz", isKeeper: false, isExtra: false },
  { round:  3, draftOrder:  9, manager: "Andrew Bergoine", player: "William Contreras", isKeeper: false, isExtra: false },
  { round:  3, draftOrder:  9, manager: "Andrew Bergoine", player: "Joe Ryan", isKeeper: false, isExtra: false },
  { round:  3, draftOrder: 10, manager: "Austin Brennen", player: "Pete Alonso", isKeeper: false, isExtra: false },
  { round:  3, draftOrder: 10, manager: "Austin Brennen", player: "Belli", isKeeper: false, isExtra: false },
  { round:  3, draftOrder: 10, manager: "Austin Brennen", player: "Bichette", isKeeper: false, isExtra: false },
  { round:  3, draftOrder: 12, manager: "Charley Tauer", player: "George Kirby", isKeeper: false, isExtra: false },
  { round:  3, draftOrder: 12, manager: "Charley Tauer", player: "Jazz Chisholm", isKeeper: false, isExtra: false },
  { round:  4, draftOrder:  3, manager: "Kevin Katsuda", player: "Pivetta", isKeeper: false, isExtra: false },
  { round:  4, draftOrder:  6, manager: "Mike Kyne", player: "Pepiot", isKeeper: false, isExtra: false },
  { round:  4, draftOrder:  7, manager: "Josh", player: "Harper", isKeeper: false, isExtra: false },
  { round:  4, draftOrder:  8, manager: "Artie Arredondo", player: "Vladimir Guerrero Jr.", isKeeper: true, isExtra: false },
  { round:  4, draftOrder:  9, manager: "Andrew Bergoine", player: "Kwan", isKeeper: false, isExtra: false },
  { round:  4, draftOrder:  9, manager: "Andrew Bergoine", player: "Altuve", isKeeper: false, isExtra: false },
  { round:  4, draftOrder: 10, manager: "Austin Brennen", player: "Luis Arraez", isKeeper: false, isExtra: false },
  { round:  4, draftOrder: 10, manager: "Austin Brennen", player: "Ragans", isKeeper: false, isExtra: false },
  { round:  4, draftOrder: 10, manager: "Austin Brennen", player: "Trea Turner", isKeeper: false, isExtra: false },
  { round:  4, draftOrder: 11, manager: "Stephan Mattke", player: "Sonny Gray", isKeeper: false, isExtra: false },
  { round:  4, draftOrder: 11, manager: "Stephan Mattke", player: "Gausman", isKeeper: false, isExtra: false },
  { round:  4, draftOrder: 12, manager: "Charley Tauer", player: "Ronald Acuna", isKeeper: true, isExtra: false },
  { round:  5, draftOrder:  1, manager: "Patrick Harvey", player: "Ben Rice", isKeeper: false, isExtra: false },
  { round:  5, draftOrder:  2, manager: "Mike Porter", player: "Tyler Glas", isKeeper: false, isExtra: false },
  { round:  5, draftOrder:  3, manager: "Kevin Katsuda", player: "Matt Olson", isKeeper: false, isExtra: false },
  { round:  5, draftOrder:  4, manager: "Will Harris", player: "Mason Miller", isKeeper: false, isExtra: false },
  { round:  5, draftOrder:  6, manager: "Mike Kyne", player: "Josh Naylor", isKeeper: false, isExtra: false },
  { round:  5, draftOrder:  7, manager: "Josh", player: "Maikel Garcia", isKeeper: false, isExtra: false },
  { round:  5, draftOrder:  8, manager: "Artie Arredondo", player: "Freeman", isKeeper: false, isExtra: false },
  { round:  5, draftOrder:  9, manager: "Andrew Bergoine", player: "Jackson Merrill", isKeeper: false, isExtra: false },
  { round:  5, draftOrder: 10, manager: "Austin Brennen", player: "Springer", isKeeper: false, isExtra: false },
  { round:  5, draftOrder: 11, manager: "Stephan Mattke", player: "Eovaldi", isKeeper: false, isExtra: false },
  { round:  5, draftOrder: 12, manager: "Charley Tauer", player: "Riley Greene", isKeeper: false, isExtra: false },
  { round:  5, draftOrder: 12, manager: "Charley Tauer", player: "Nolan McLain", isKeeper: false, isExtra: false },
  { round:  6, draftOrder:  3, manager: "Kevin Katsuda", player: "Spencer Strider", isKeeper: false, isExtra: false },
  { round:  6, draftOrder:  4, manager: "Will Harris", player: "Hunter Goodman", isKeeper: false, isExtra: false },
  { round:  6, draftOrder:  5, manager: "Darren Cook", player: "Teoscar Hernández", isKeeper: false, isExtra: false },
  { round:  6, draftOrder:  5, manager: "Darren Cook", player: "Robbie Ray", isKeeper: false, isExtra: false },
  { round:  6, draftOrder:  6, manager: "Mike Kyne", player: "Eugenio Suarez", isKeeper: false, isExtra: false },
  { round:  6, draftOrder:  7, manager: "Josh", player: "Julio Rodriguez", isKeeper: true, isExtra: false },
  { round:  6, draftOrder:  8, manager: "Artie Arredondo", player: "Luis Castillo", isKeeper: false, isExtra: false },
  { round:  6, draftOrder:  9, manager: "Andrew Bergoine", player: "Seager", isKeeper: false, isExtra: false },
  { round:  6, draftOrder: 10, manager: "Austin Brennen", player: "Geraldo Perdomo", isKeeper: false, isExtra: false },
  { round:  6, draftOrder: 11, manager: "Stephan Mattke", player: "Austin Riley", isKeeper: false, isExtra: false },
  { round:  6, draftOrder: 12, manager: "Charley Tauer", player: "Drew Rasmussen", isKeeper: false, isExtra: false },
  { round:  6, draftOrder: 12, manager: "Charley Tauer", player: "CJ Abrams", isKeeper: false, isExtra: false },
  { round:  7, draftOrder:  1, manager: "Patrick Harvey", player: "Snell", isKeeper: false, isExtra: false },
  { round:  7, draftOrder:  2, manager: "Mike Porter", player: "Alcantara", isKeeper: false, isExtra: false },
  { round:  7, draftOrder:  3, manager: "Kevin Katsuda", player: "Yandy Diaz", isKeeper: false, isExtra: false },
  { round:  7, draftOrder:  4, manager: "Will Harris", player: "Brice Turang", isKeeper: false, isExtra: false },
  { round:  7, draftOrder:  5, manager: "Darren Cook", player: "Cal Raleigh", isKeeper: true, isExtra: false },
  { round:  7, draftOrder:  6, manager: "Mike Kyne", player: "Brandon Nimmo", isKeeper: false, isExtra: false },
  { round:  7, draftOrder:  7, manager: "Josh", player: "Juan Soto", isKeeper: true, isExtra: false },
  { round:  7, draftOrder:  7, manager: "Josh", player: "Bryan Woo", isKeeper: true, isExtra: false },
  { round:  7, draftOrder:  8, manager: "Artie Arredondo", player: "Buxton", isKeeper: false, isExtra: false },
  { round:  7, draftOrder:  9, manager: "Andrew Bergoine", player: "Sal Perez", isKeeper: false, isExtra: false },
  { round:  7, draftOrder: 11, manager: "Stephan Mattke", player: "Soderstrom", isKeeper: false, isExtra: false },
  { round:  7, draftOrder: 12, manager: "Charley Tauer", player: "King", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  1, manager: "Patrick Harvey", player: "Ozzie Albies", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  2, manager: "Mike Porter", player: "Trevor Rogers", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  3, manager: "Kevin Katsuda", player: "Jacob Wilson", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  3, manager: "Kevin Katsuda", player: "Lodolo", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  4, manager: "Will Harris", player: "Alec Burleson", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  5, manager: "Darren Cook", player: "Nola", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  6, manager: "Mike Kyne", player: "Bibee", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  8, manager: "Artie Arredondo", player: "Gallen", isKeeper: false, isExtra: false },
  { round:  8, draftOrder:  9, manager: "Andrew Bergoine", player: "Suzuki", isKeeper: false, isExtra: false },
  { round:  8, draftOrder: 11, manager: "Stephan Mattke", player: "Tatsuya Imai", isKeeper: false, isExtra: false },
  { round:  8, draftOrder: 12, manager: "Charley Tauer", player: "Shea Langliers", isKeeper: false, isExtra: false },
  { round:  8, draftOrder: 12, manager: "Charley Tauer", player: "Kazuma Okamoto", isKeeper: false, isExtra: false },
  { round:  9, draftOrder:  2, manager: "Mike Porter", player: "Yelich", isKeeper: false, isExtra: false },
  { round:  9, draftOrder:  2, manager: "Mike Porter", player: "Wheeler", isKeeper: false, isExtra: false },
  { round:  9, draftOrder:  4, manager: "Will Harris", player: "Edwin Díaz", isKeeper: false, isExtra: false },
  { round:  9, draftOrder:  5, manager: "Darren Cook", player: "Stowers", isKeeper: false, isExtra: false },
  { round:  9, draftOrder:  6, manager: "Mike Kyne", player: "Adell", isKeeper: false, isExtra: false },
  { round:  9, draftOrder:  7, manager: "Josh", player: "Imanaga", isKeeper: false, isExtra: false },
  { round:  9, draftOrder:  8, manager: "Artie Arredondo", player: "Arozarena", isKeeper: false, isExtra: false },
  { round:  9, draftOrder:  9, manager: "Andrew Bergoine", player: "Ranger Suarez", isKeeper: false, isExtra: false },
  { round:  9, draftOrder: 10, manager: "Austin Brennen", player: "Logan Webb", isKeeper: true, isExtra: false },
  { round:  9, draftOrder: 10, manager: "Austin Brennen", player: "Gavin Williams", isKeeper: false, isExtra: false },
  { round:  9, draftOrder: 11, manager: "Stephan Mattke", player: "Augustin Ramirez", isKeeper: false, isExtra: false },
  { round:  9, draftOrder: 12, manager: "Charley Tauer", player: "Oneil Cruz", isKeeper: false, isExtra: false },
  { round: 10, draftOrder:  1, manager: "Patrick Harvey", player: "Matt Chapman", isKeeper: false, isExtra: false },
  { round: 10, draftOrder:  3, manager: "Kevin Katsuda", player: "Gore", isKeeper: false, isExtra: false },
  { round: 10, draftOrder:  4, manager: "Will Harris", player: "Cag", isKeeper: false, isExtra: false },
  { round: 10, draftOrder:  6, manager: "Mike Kyne", player: "Reynolds", isKeeper: false, isExtra: false },
  { round: 10, draftOrder:  7, manager: "Josh", player: "Abbott", isKeeper: false, isExtra: false },
  { round: 10, draftOrder:  7, manager: "Josh", player: "Pena", isKeeper: false, isExtra: false },
  { round: 10, draftOrder:  9, manager: "Andrew Bergoine", player: "Munoz", isKeeper: false, isExtra: false },
  { round: 10, draftOrder: 10, manager: "Austin Brennen", player: "Carlos Rodón", isKeeper: false, isExtra: false },
  { round: 10, draftOrder: 10, manager: "Austin Brennen", player: "Sheehan", isKeeper: false, isExtra: false },
  { round: 10, draftOrder: 10, manager: "Austin Brennen", player: "Cade Smith", isKeeper: false, isExtra: false },
  { round: 10, draftOrder: 12, manager: "Charley Tauer", player: "Jho Duran", isKeeper: false, isExtra: false },
  { round: 10, draftOrder: 12, manager: "Charley Tauer", player: "Yesavage", isKeeper: false, isExtra: false },
  { round: 11, draftOrder:  1, manager: "Patrick Harvey", player: "Adley Rutschman", isKeeper: false, isExtra: false },
  { round: 11, draftOrder:  2, manager: "Mike Porter", player: "Stewart", isKeeper: false, isExtra: false },
  { round: 11, draftOrder:  2, manager: "Mike Porter", player: "Keaschall", isKeeper: false, isExtra: false },
  { round: 11, draftOrder:  3, manager: "Kevin Katsuda", player: "Baldwin", isKeeper: false, isExtra: false },
  { round: 11, draftOrder:  7, manager: "Josh", player: "Bubic", isKeeper: false, isExtra: false },
  { round: 11, draftOrder:  8, manager: "Artie Arredondo", player: "Baz", isKeeper: false, isExtra: false },
  { round: 11, draftOrder:  9, manager: "Andrew Bergoine", player: "Happ", isKeeper: false, isExtra: false },
  { round: 11, draftOrder:  9, manager: "Andrew Bergoine", player: "Devin Williams", isKeeper: false, isExtra: false },
  { round: 11, draftOrder: 10, manager: "Austin Brennen", player: "Boyd", isKeeper: false, isExtra: false },
  { round: 11, draftOrder: 11, manager: "Stephan Mattke", player: "Adames", isKeeper: false, isExtra: false },
  { round: 11, draftOrder: 12, manager: "Charley Tauer", player: "Bednar", isKeeper: false, isExtra: false },
  { round: 11, draftOrder: 12, manager: "Charley Tauer", player: "Woodruff", isKeeper: false, isExtra: false },
  { round: 12, draftOrder:  1, manager: "Patrick Harvey", player: "Aroldis Chapman", isKeeper: false, isExtra: false },
  { round: 12, draftOrder:  3, manager: "Kevin Katsuda", player: "Michael Harris II", isKeeper: false, isExtra: false },
  { round: 12, draftOrder:  3, manager: "Kevin Katsuda", player: "Will Smith", isKeeper: false, isExtra: false },
  { round: 12, draftOrder:  4, manager: "Will Harris", player: "Andy Pages", isKeeper: false, isExtra: false },
  { round: 12, draftOrder:  7, manager: "Josh", player: "Weathers", isKeeper: false, isExtra: false },
  { round: 12, draftOrder:  8, manager: "Artie Arredondo", player: "Yanier Diaz", isKeeper: false, isExtra: false },
  { round: 12, draftOrder:  9, manager: "Andrew Bergoine", player: "Iglesias", isKeeper: false, isExtra: false },
  { round: 12, draftOrder:  9, manager: "Andrew Bergoine", player: "Tovar", isKeeper: false, isExtra: false },
  { round: 12, draftOrder: 10, manager: "Austin Brennen", player: "Paredes", isKeeper: false, isExtra: false },
  { round: 12, draftOrder: 10, manager: "Austin Brennen", player: "Abreu", isKeeper: false, isExtra: false },
  { round: 12, draftOrder: 11, manager: "Stephan Mattke", player: "Leiter", isKeeper: false, isExtra: false },
  { round: 12, draftOrder: 12, manager: "Charley Tauer", player: "Walker", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  1, manager: "Patrick Harvey", player: "Jack Flaherty", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  3, manager: "Kevin Katsuda", player: "Cole", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  4, manager: "Will Harris", player: "Jorge Polanco", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  5, manager: "Darren Cook", player: "Shane Maclanahan", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  5, manager: "Darren Cook", player: "Luis Robert", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  6, manager: "Mike Kyne", player: "Holliday", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  7, manager: "Josh", player: "Senga", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  8, manager: "Artie Arredondo", player: "Lile", isKeeper: false, isExtra: false },
  { round: 13, draftOrder:  9, manager: "Andrew Bergoine", player: "Marsee", isKeeper: false, isExtra: false },
  { round: 13, draftOrder: 10, manager: "Austin Brennen", player: "E Cabrera", isKeeper: false, isExtra: false },
  { round: 13, draftOrder: 11, manager: "Stephan Mattke", player: "Griffin", isKeeper: false, isExtra: false },
  { round: 13, draftOrder: 11, manager: "Stephan Mattke", player: "Matt McClain", isKeeper: false, isExtra: false },
  { round: 14, draftOrder:  2, manager: "Mike Porter", player: "Murakami", isKeeper: false, isExtra: false },
  { round: 14, draftOrder:  4, manager: "Will Harris", player: "Jose Soriano", isKeeper: false, isExtra: false },
  { round: 14, draftOrder:  5, manager: "Darren Cook", player: "Lugo", isKeeper: false, isExtra: false },
  { round: 14, draftOrder:  5, manager: "Darren Cook", player: "Heliot Ramos", isKeeper: false, isExtra: false },
  { round: 14, draftOrder:  6, manager: "Mike Kyne", player: "Carpenter", isKeeper: false, isExtra: false },
  { round: 14, draftOrder:  7, manager: "Josh", player: "Ivan Herrera", isKeeper: false, isExtra: false },
  { round: 14, draftOrder:  7, manager: "Josh", player: "Aranda", isKeeper: false, isExtra: false },
  { round: 14, draftOrder:  9, manager: "Andrew Bergoine", player: "Frelick", isKeeper: false, isExtra: false },
  { round: 14, draftOrder: 10, manager: "Austin Brennen", player: "Griffin Jax", isKeeper: false, isExtra: false },
  { round: 14, draftOrder: 10, manager: "Austin Brennen", player: "Gleybar Torres", isKeeper: false, isExtra: false },
  { round: 14, draftOrder: 11, manager: "Stephan Mattke", player: "Dansby Swanson", isKeeper: false, isExtra: false },
  { round: 14, draftOrder: 12, manager: "Charley Tauer", player: "B. Lowe", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  2, manager: "Mike Porter", player: "Noah Cameron", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  2, manager: "Mike Porter", player: "Ryne Nelson", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  2, manager: "Mike Porter", player: "Varsho", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  5, manager: "Darren Cook", player: "Donovan", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  6, manager: "Mike Kyne", player: "Rafaela", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  6, manager: "Mike Kyne", player: "Grayson Rodríguez", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  7, manager: "Josh", player: "Warren", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  7, manager: "Josh", player: "Wetherholt", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  8, manager: "Artie Arredondo", player: "Basallo", isKeeper: false, isExtra: false },
  { round: 15, draftOrder:  9, manager: "Andrew Bergoine", player: "Cantillo", isKeeper: false, isExtra: false },
  { round: 15, draftOrder: 10, manager: "Austin Brennen", player: "Jacob de Grom", isKeeper: true, isExtra: false },
  { round: 15, draftOrder: 12, manager: "Charley Tauer", player: "Ponce", isKeeper: false, isExtra: false },
  { round: 15, draftOrder: 12, manager: "Charley Tauer", player: "Hader", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  1, manager: "Patrick Harvey", player: "Jung Hoo Lee", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  2, manager: "Mike Porter", player: "Burrows", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  3, manager: "Kevin Katsuda", player: "Xavier Edwards", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  4, manager: "Will Harris", player: "McGonigal", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  4, manager: "Will Harris", player: "Addison Barger", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  5, manager: "Darren Cook", player: "Willson Contreras", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  6, manager: "Mike Kyne", player: "Fairbanks", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  7, manager: "Josh", player: "Efliin", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  8, manager: "Artie Arredondo", player: "Semien", isKeeper: false, isExtra: false },
  { round: 16, draftOrder:  9, manager: "Andrew Bergoine", player: "Bieber", isKeeper: false, isExtra: false },
  { round: 16, draftOrder: 10, manager: "Austin Brennen", player: "Carter Jensen", isKeeper: false, isExtra: false },
  { round: 16, draftOrder: 11, manager: "Stephan Mattke", player: "Pagan", isKeeper: false, isExtra: false },
  { round: 17, draftOrder:  1, manager: "Patrick Harvey", player: "Joe Musgrove", isKeeper: false, isExtra: false },
  { round: 17, draftOrder:  2, manager: "Mike Porter", player: "Harrison", isKeeper: false, isExtra: false },
  { round: 17, draftOrder:  3, manager: "Kevin Katsuda", player: "Clement", isKeeper: false, isExtra: false },
  { round: 17, draftOrder:  4, manager: "Will Harris", player: "Liberatore", isKeeper: false, isExtra: false },
  { round: 17, draftOrder:  5, manager: "Darren Cook", player: "Kikuchi", isKeeper: false, isExtra: false },
  { round: 17, draftOrder:  6, manager: "Mike Kyne", player: "Jesus Luzardo", isKeeper: true, isExtra: false },
  { round: 17, draftOrder:  7, manager: "Josh", player: "Merrill Kelly", isKeeper: false, isExtra: false },
  { round: 17, draftOrder:  8, manager: "Artie Arredondo", player: "Henderson", isKeeper: false, isExtra: false },
  { round: 17, draftOrder:  9, manager: "Andrew Bergoine", player: "Westburg", isKeeper: false, isExtra: false },
  { round: 17, draftOrder: 11, manager: "Stephan Mattke", player: "Bryce Miller", isKeeper: false, isExtra: false },
  { round: 17, draftOrder: 11, manager: "Stephan Mattke", player: "Shane Smith", isKeeper: false, isExtra: false },
  { round: 17, draftOrder: 12, manager: "Charley Tauer", player: "Caballero", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  1, manager: "Patrick Harvey", player: "Trevor Story", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  1, manager: "Patrick Harvey", player: "Adolis Garcia", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  2, manager: "Mike Porter", player: "Abel", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  3, manager: "Kevin Katsuda", player: "Noelvi Marte", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  3, manager: "Kevin Katsuda", player: "Brayan Bello", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  4, manager: "Will Harris", player: "Cavalli", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  4, manager: "Will Harris", player: "Lawrence Butler", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  5, manager: "Darren Cook", player: "Durbin", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  6, manager: "Mike Kyne", player: "Kirk", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  7, manager: "Josh", player: "Painter", isKeeper: false, isExtra: false },
  { round: 18, draftOrder:  8, manager: "Artie Arredondo", player: "Braxton Ashcraft", isKeeper: false, isExtra: false },
  { round: 19, draftOrder:  1, manager: "Patrick Harvey", player: "Roman Anthony", isKeeper: true, isExtra: false },
  { round: 19, draftOrder:  1, manager: "Patrick Harvey", player: "Dylan Crews", isKeeper: false, isExtra: false },
  { round: 19, draftOrder:  2, manager: "Mike Porter", player: "F. Alvarez", isKeeper: false, isExtra: false },
  { round: 19, draftOrder:  2, manager: "Mike Porter", player: "Laureano", isKeeper: false, isExtra: false },
  { round: 19, draftOrder:  3, manager: "Kevin Katsuda", player: "Estrada", isKeeper: false, isExtra: false },
  { round: 19, draftOrder:  5, manager: "Darren Cook", player: "Buehler", isKeeper: false, isExtra: false },
  { round: 19, draftOrder:  6, manager: "Mike Kyne", player: "Meyer", isKeeper: false, isExtra: false },
  { round: 19, draftOrder:  8, manager: "Artie Arredondo", player: "Trout", isKeeper: false, isExtra: false },
  { round: 19, draftOrder:  8, manager: "Artie Arredondo", player: "Lawlar", isKeeper: false, isExtra: false },
  { round: 19, draftOrder: 11, manager: "Stephan Mattke", player: "Chase DeLauter", isKeeper: false, isExtra: false },
  { round: 19, draftOrder: 11, manager: "Stephan Mattke", player: "Ozuna", isKeeper: false, isExtra: false },
  { round: 20, draftOrder:  1, manager: "Patrick Harvey", player: "Brenton Doyle", isKeeper: false, isExtra: false },
  { round: 20, draftOrder:  1, manager: "Patrick Harvey", player: "Tolle", isKeeper: false, isExtra: false },
  { round: 20, draftOrder:  2, manager: "Mike Porter", player: "James Wood", isKeeper: true, isExtra: false },
  { round: 20, draftOrder:  3, manager: "Kevin Katsuda", player: "Junior Caminero", isKeeper: true, isExtra: false },
  { round: 20, draftOrder:  3, manager: "Kevin Katsuda", player: "Brent Rooker", isKeeper: true, isExtra: false },
  { round: 20, draftOrder:  4, manager: "Will Harris", player: "Garrett Crochet", isKeeper: true, isExtra: false },
  { round: 20, draftOrder:  5, manager: "Darren Cook", player: "Carlos Correa", isKeeper: false, isExtra: false },
  { round: 20, draftOrder:  6, manager: "Mike Kyne", player: "Grant Taylor", isKeeper: false, isExtra: false },
  { round: 20, draftOrder:  7, manager: "Josh", player: "Moreno", isKeeper: false, isExtra: false },
  { round: 20, draftOrder:  8, manager: "Artie Arredondo", player: "Ryan Helsley", isKeeper: false, isExtra: false },
  { round: 20, draftOrder: 10, manager: "Austin Brennen", player: "Wilyer Abreu", isKeeper: false, isExtra: false },
  { round: 20, draftOrder: 11, manager: "Stephan Mattke", player: "Bassitt", isKeeper: false, isExtra: false },
  { round: 21, draftOrder:  1, manager: "Patrick Harvey", player: "Carlos Estevez", isKeeper: false, isExtra: false },
  { round: 21, draftOrder:  2, manager: "Mike Porter", player: "Hunter Greene", isKeeper: false, isExtra: false },
  { round: 21, draftOrder:  3, manager: "Kevin Katsuda", player: "Abner Uribe", isKeeper: false, isExtra: false },
  { round: 21, draftOrder:  4, manager: "Will Harris", player: "Dustin May", isKeeper: false, isExtra: false },
  { round: 21, draftOrder:  4, manager: "Will Harris", player: "Brandon Sproat", isKeeper: false, isExtra: false },
  { round: 21, draftOrder:  5, manager: "Darren Cook", player: "Eldridge", isKeeper: false, isExtra: false },
  { round: 21, draftOrder:  8, manager: "Artie Arredondo", player: "Leo De Vries", isKeeper: false, isExtra: false },
  { round: 21, draftOrder: 11, manager: "Stephan Mattke", player: "Pete Crow-Armstrong", isKeeper: true, isExtra: false },
  { round: 21, draftOrder: 11, manager: "Stephan Mattke", player: "Hoffman", isKeeper: false, isExtra: false },
  { round: 22, draftOrder:  1, manager: "Patrick Harvey", player: "Jasson Dominguez", isKeeper: false, isExtra: false },
  { round: 22, draftOrder:  2, manager: "Mike Porter", player: "Arrighetti", isKeeper: false, isExtra: false },
  { round: 22, draftOrder:  3, manager: "Kevin Katsuda", player: "Singer", isKeeper: false, isExtra: false },
  { round: 22, draftOrder:  3, manager: "Kevin Katsuda", player: "Ben Brown", isKeeper: false, isExtra: false },
  { round: 22, draftOrder:  4, manager: "Will Harris", player: "Brett Baty", isKeeper: false, isExtra: false },
  { round: 22, draftOrder:  5, manager: "Darren Cook", player: "Reynaldo Lopez", isKeeper: false, isExtra: false },
  { round: 22, draftOrder:  8, manager: "Artie Arredondo", player: "Sasaki", isKeeper: false, isExtra: false },
  { round: 22, draftOrder:  9, manager: "Andrew Bergoine", player: "Nico Hoerner", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  1, manager: "Patrick Harvey", player: "Garrett Whitlock", isKeeper: false, isExtra: false },
  { round: 23, draftOrder:  2, manager: "Mike Porter", player: "Wyatt Langford", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  3, manager: "Kevin Katsuda", player: "Jarren Duran", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  4, manager: "Will Harris", player: "Kyle Bradish", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  4, manager: "Will Harris", player: "Zach Neto", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  5, manager: "Darren Cook", player: "Eury Perez", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  6, manager: "Mike Kyne", player: "Michael Busch", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  6, manager: "Mike Kyne", player: "Chase Burns", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  7, manager: "Josh", player: "Messick", isKeeper: false, isExtra: false },
  { round: 23, draftOrder:  8, manager: "Artie Arredondo", player: "Bubba Chandler", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  9, manager: "Andrew Bergoine", player: "Spencer Torkelson", isKeeper: true, isExtra: false },
  { round: 23, draftOrder:  9, manager: "Andrew Bergoine", player: "Cade Horton", isKeeper: true, isExtra: false },
  { round: 23, draftOrder: 10, manager: "Austin Brennen", player: "Nick Kurtz", isKeeper: true, isExtra: false },
  { round: 23, draftOrder: 11, manager: "Stephan Mattke", player: "Taylor Ward", isKeeper: true, isExtra: false },
  { round: 23, draftOrder: 11, manager: "Stephan Mattke", player: "Cam Schlittler", isKeeper: true, isExtra: false },
  { round: 23, draftOrder: 12, manager: "Charley Tauer", player: "Jacob Misiorowski", isKeeper: true, isExtra: false },
  { round: 23, draftOrder: 12, manager: "Charley Tauer", player: "Vinnie Pasquantino", isKeeper: true, isExtra: false },
  { round: 24, draftOrder:  1, manager: "Patrick Harvey", player: "Trevor Larnach", isKeeper: false, isExtra: false },
  { round: 24, draftOrder:  1, manager: "Patrick Harvey", player: "Joey Loperfido", isKeeper: false, isExtra: false },
  { round: 24, draftOrder:  2, manager: "Mike Porter", player: "Megill", isKeeper: false, isExtra: false },
  { round: 24, draftOrder:  4, manager: "Will Harris", player: "Jared Jones", isKeeper: false, isExtra: false },
  { round: 24, draftOrder:  5, manager: "Darren Cook", player: "Cristian Javier", isKeeper: false, isExtra: false },
  { round: 24, draftOrder:  6, manager: "Mike Kyne", player: "Taj Bradley", isKeeper: false, isExtra: false },
  { round: 24, draftOrder:  7, manager: "Josh", player: "Schwellenbach", isKeeper: false, isExtra: false },
  { round: 24, draftOrder:  8, manager: "Artie Arredondo", player: "Palencia", isKeeper: false, isExtra: false },
  { round: 24, draftOrder: 11, manager: "Stephan Mattke", player: "J Springs", isKeeper: false, isExtra: false },
  { round: 25, draftOrder:  1, manager: "Patrick Harvey", player: "Puk", isKeeper: false, isExtra: false },
  { round: 25, draftOrder:  2, manager: "Mike Porter", player: "Kenley Jansen", isKeeper: false, isExtra: false },
  { round: 25, draftOrder:  4, manager: "Will Harris", player: "Drew Anderson", isKeeper: false, isExtra: false },
  { round: 25, draftOrder:  5, manager: "Darren Cook", player: "Cam Smith", isKeeper: false, isExtra: false },
  { round: 25, draftOrder:  6, manager: "Mike Kyne", player: "Cleavinger", isKeeper: false, isExtra: false },
  { round: 25, draftOrder:  7, manager: "Josh", player: "Cowser", isKeeper: false, isExtra: false },
  { round: 25, draftOrder:  8, manager: "Artie Arredondo", player: "Josh Smith", isKeeper: false, isExtra: false },
  { round: 25, draftOrder: 11, manager: "Stephan Mattke", player: "Miguel Vargas", isKeeper: false, isExtra: false },
  { round: 26, draftOrder:  1, manager: "Patrick Harvey", player: "Holderman", isKeeper: false, isExtra: true },
  { round: 26, draftOrder:  2, manager: "Mike Porter", player: "Adrian Morejon", isKeeper: false, isExtra: true },
  { round: 26, draftOrder:  4, manager: "Will Harris", player: "Johan Oviedo", isKeeper: false, isExtra: true },
  { round: 26, draftOrder:  5, manager: "Darren Cook", player: "Coby Mayo", isKeeper: false, isExtra: true },
  { round: 26, draftOrder:  6, manager: "Mike Kyne", player: "Ober", isKeeper: false, isExtra: true },
  { round: 26, draftOrder:  8, manager: "Artie Arredondo", player: "Seranthony Dominguez", isKeeper: false, isExtra: true },
  { round: 27, draftOrder:  5, manager: "Darren Cook", player: "Marcelo Mayer", isKeeper: false, isExtra: true },
  { round: 27, draftOrder:  6, manager: "Mike Kyne", player: "Benge", isKeeper: false, isExtra: true },
  { round: 28, draftOrder:  5, manager: "Darren Cook", player: "Corbin Burns", isKeeper: false, isExtra: true },
  { round: 29, draftOrder:  5, manager: "Darren Cook", player: "Ryan Walker", isKeeper: false, isExtra: true },
];
